# -*- coding: utf-8 -*-
"""test.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18tQoOdmmyjp9IJVzEglbLNVij8eCqoEd
"""

# Підключаємо Google Drive
from google.colab import drive
drive.mount('/content/drive')
from pathlib import Path

# 🔁 Вкажи свій реальний шлях до папки на Google Диску
# Наприклад, якщо повний шлях: /MyDrive/test/dataset
folder_path = Path("/content/drive/MyDrive/test/dataset/mobs")

# Підрахунок .jpg файлів рекурсивно
image_count = len(list(folder_path.rglob("*.jpg")))
print(f"🖼️ Кількість .jpg зображень: {image_count}")

from google.colab import drive
drive.mount('/content/drive')
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np
import PIL
import tensorflow as tf
from keras.layers import Rescaling

from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras.models import Sequential

dataset_dir = Path("/content/drive/MyDrive/test/dataset/mobs")
batch_size = 16
img_width = 256
img_height = 256

train_ds = tf.keras.utils.image_dataset_from_directory(
    dataset_dir,
    validation_split = 0.2,
    subset = "training",
    seed = 123,
    image_size = (img_height, img_width),
    batch_size = batch_size)

val_ds = tf.keras.utils.image_dataset_from_directory(
    dataset_dir,
    validation_split = 0.2,
    subset = "validation",
    seed = 123,
    image_size = (img_height, img_width),
    batch_size = batch_size)

class_names = train_ds.class_names
print(f"Class names: {class_names} ")

#cache
AUTOTUNE = tf.data.AUTOTUNE

train_ds = train_ds.cache().shuffle(1000).prefetch(buffer_size=AUTOTUNE)
val_ds = val_ds.cache().prefetch(buffer_size=AUTOTUNE)

#create model
num_classes = len(class_names)
model = Sequential([
  layers.Rescaling(1./255, input_shape=(img_height, img_width, 3)),

  #augementation
  layers.RandomFlip("horizontal",
                    input_shape=(img_height,
                                 img_width,
                                 3)),
  layers.RandomRotation(0.1),
  layers.RandomZoom(0.1),
  layers.RandomContrast(0.2),

  #regulization
  layers.Dropout(0.2),

  layers.Conv2D(16, 3, padding='same', activation='relu'),
  layers.MaxPooling2D(),

  layers.Conv2D(32, 3, padding='same', activation='relu'),
  layers.MaxPooling2D(),

  layers.Conv2D(64, 3, padding='same', activation='relu'),
  layers.MaxPooling2D(),

  layers.Flatten(),
  layers.Dense(128, activation='relu'),
  layers.Dense(num_classes)
])

#compile model
model.compile(optimizer='adam',
              loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True),
              metrics=['accuracy'])
model.summary()



#train model
epochs=15
history = model.fit(
  train_ds,
  validation_data=val_ds,
  epochs=epochs
)

# visualize training and validation results
acc = history.history['accuracy']
val_acc = history.history['val_accuracy']

loss = history.history['loss']
val_loss = history.history['val_loss']

epochs_range = range(epochs)

plt.figure(figsize=(8, 8))
plt.subplot(1, 2, 1)
plt.plot(epochs_range, acc, label='Training Accuracy')
plt.plot(epochs_range, val_acc, label='Validation Accuracy')
plt.legend(loc='lower right')
plt.title('Training and Validation Accuracy')

plt.subplot(1, 2, 2)
plt.plot(epochs_range, loss, label='Training Loss')
plt.plot(epochs_range, val_loss, label='Validation Loss')
plt.legend(loc='upper right')
plt.title('Training and Validation Loss')
plt.show()


model.save_weights('/content/drive/MyDrive/test/yolo/mobs.weights.h5')
print("Model saved")

import tensorflow as tf
import numpy as np
from tensorflow.keras.utils import load_img, img_to_array
from PIL import Image

# Параметри моделі
img_height = 256
img_width = 256

# Шлях до зображення
image_path = "/content/drive/MyDrive/test/yolo/second.png"

# Завантаження та підготовка зображення
img = load_img(image_path, target_size=(img_height, img_width))
img_array = img_to_array(img)
img_array = tf.expand_dims(img_array, 0)  # [1, height, width, 3]

# Передбачення
predictions = model.predict(img_array)
score = tf.nn.softmax(predictions[0])

# Вивід результату
print("На изображении скорее всего {} ({:.2f}% вероятность)".format(
    class_names[np.argmax(score)],
    100 * np.max(score)))

# Показ зображення
img = Image.open(image_path)
img.show()

# 1. Підключення Google Drive
from google.colab import drive
drive.mount('/content/drive')
# 2. Імпорти
import matplotlib.pyplot as plt
import tensorflow as tf
from tensorflow.keras import layers, models
from tensorflow.keras.utils import image_dataset_from_directory, load_img, img_to_array
import numpy as np
import matplotlib.pyplot as plt
# 3. Параметри
dataset_dir = "/content/drive/MyDrive/test/dataset"  # тут повинні бути папки mobs/ і empty/
img_height = 256
img_width = 256
batch_size = 16
# 4. Завантаження датасету (бінарна класифікація)
train_ds = image_dataset_from_directory(
    dataset_dir,
    validation_split=0.2,
    subset="training",
    seed=123,
    image_size=(img_height, img_width),
    batch_size=batch_size,
    label_mode='binary'
)

val_ds = image_dataset_from_directory(
    dataset_dir,
    validation_split=0.2,
    subset="validation",
    seed=123,
    image_size=(img_height, img_width),
    batch_size=batch_size,
    label_mode='binary'
)
# 5. Оптимізація pipeline
AUTOTUNE = tf.data.AUTOTUNE
train_ds = train_ds.shuffle(1000).prefetch(buffer_size=AUTOTUNE)
val_ds = val_ds.prefetch(buffer_size=AUTOTUNE)
# 6. Побудова моделі
model = models.Sequential([
    layers.Rescaling(1./255, input_shape=(img_height, img_width, 3)),

    layers.Conv2D(16, 3, activation='relu'),
    layers.MaxPooling2D(),

    layers.Conv2D(32, 3, activation='relu'),
    layers.MaxPooling2D(),

    layers.Conv2D(64, 3, activation='relu'),
    layers.MaxPooling2D(),

    layers.Flatten(),
    layers.Dense(64, activation='relu'),
    layers.Dense(1, activation='sigmoid')  # один нейрон для ймовірності
])

# 7. Компіляція моделі
model.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)
# 8. Навчання
epochs = 15
history = model.fit(
    train_ds,
    validation_data=val_ds,
    epochs=epochs
)
# 9. Графіки точності
plt.plot(history.history['accuracy'], label='Train Accuracy')
plt.plot(history.history['val_accuracy'], label='Validation Accuracy')
plt.legend()
plt.title('Accuracy over Epochs')
plt.show()
# 10. Збереження ваг у Google Drive
model.save_weights('/content/drive/MyDrive/test/yolo/mob_classifier.weights.h5')

# шлях до скріна
image_path = "/content/drive/MyDrive/test/yolo/Shot3.jpg"

# підготовка
img = load_img(image_path, target_size=(img_height, img_width))
img_array = img_to_array(img)
img_array = tf.expand_dims(img_array, 0)

# передбачення
prediction = model.predict(img_array)
prob = prediction[0][0]

# результат
if prob > 0.5:
    print(f"✅ На скріншоті є моб! ({prob:.2f})")
else:
    print(f"❌ Моб не знайдено. ({prob:.2f})")

# показ зображення
plt.imshow(img)
plt.axis('off')  # прибрати координатну сітку
plt.title("Скріншот для розпізнавання")
plt.show()